execute rotated ~ 0 positioned ^ ^ ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^ ^1 ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^ ^2 ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^-1 ^ ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^-1 ^1 ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^-1 ^2 ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^1 ^ ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^1 ^1 ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute rotated ~ 0 positioned ^1 ^2 ^1 run summon item_display ~ ~ ~ {Tags:["mob_life_time","skill_temp"],Passengers:[{id:"minecraft:shulker",Silent:1b,Invulnerable:1b,NoAI:1b,DeathLootTable:"dummy",AttachFace:0b,Tags:["is_passengers","friendry","skill_temp"],Passengers:[{id:"minecraft:item_display",Tags:["is_passengers","skill_temp"],transformation:{left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],translation:[0f,0f,0f],scale:[1f,1f,1f]},item:{id:"minecraft:bricks",count:1}}],active_effects:[{id:"minecraft:invisibility",amplifier:0,duration:-1,show_particles:0b}]}]}
execute as @e[tag=skill_temp] run function sys:gun_main/projectile/turret/wall_sub
