give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ハンドガン","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g1_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ハンドガン","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g1_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ハンドガン","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g1_2"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["マシンガン","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g2_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["マシンガン","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g2_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["マシンガン","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g2_2"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スナイパーライフル","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g3_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スナイパーライフル","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g3_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スナイパーライフル","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g3_2"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ショットガン","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g4_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ショットガン","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g4_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ショットガン","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g4_2"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["アサルトライフル","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g5_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["アサルトライフル","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g5_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["アサルトライフル","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_g5_2"}}']},is_waxed:1b}] 1


give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["グレネード","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s1_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["グレネード","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s1_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["グレネード","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s1_2"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["グレネード","×","3"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s1_3"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["グレネード","×","4"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s1_4"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["グレネード","×","5"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s1_5"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スモーク","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s2_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スモーク","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s2_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スモーク","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s2_2"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スモーク","×","3"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s2_3"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スモーク","×","4"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s2_4"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["スモーク","×","5"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s2_5"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ウォール","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s3_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ウォール","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s3_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ウォール","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s3_2"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ウォール","×","3"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s3_3"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ウォール","×","4"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s3_4"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ウォール","×","5"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s3_5"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ビーコン","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s4_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ビーコン","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s4_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ビーコン","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s4_2"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ビーコン","×","3"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s4_3"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ビーコン","×","4"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s4_4"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["ビーコン","×","5"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s4_5"}}']},is_waxed:1b}] 1

give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["トラップ","×","0"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s5_0"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["トラップ","×","1"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s5_1"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["トラップ","×","2"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s5_2"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["トラップ","×","3"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s5_3"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["トラップ","×","4"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s5_4"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','["トラップ","×","5"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/function sys:lobby/set_item/set_s5_5"}}']},is_waxed:1b}] 1


give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','[{"text":"最大HP","clickEvent":{"action":"run_command","value":"/scoreboard players set @s HP_max 5"}},"：","5"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/effect give @s minecraft:instant_health 1 20"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','[{"text":"最大HP","clickEvent":{"action":"run_command","value":"/scoreboard players set @s HP_max 10"}},"：","10"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/effect give @s minecraft:instant_health 1 20"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','[{"text":"最大HP","clickEvent":{"action":"run_command","value":"/scoreboard players set @s HP_max 15"}},"：","15"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/effect give @s minecraft:instant_health 1 20"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','[{"text":"最大HP","clickEvent":{"action":"run_command","value":"/scoreboard players set @s HP_max 20"}},"：","20"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/effect give @s minecraft:instant_health 1 20"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','[{"text":"最大HP","clickEvent":{"action":"run_command","value":"/scoreboard players set @s HP_max 25"}},"：","25"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/effect give @s minecraft:instant_health 1 20"}}']},is_waxed:1b}] 1
give @p dark_oak_sign[block_entity_data={id:"dark_oak_sign",front_text:{color:"white",has_glowing_text:1b,messages:['{"text":""}','[{"text":"最大HP","clickEvent":{"action":"run_command","value":"/scoreboard players set @s HP_max 30"}},"：","30"]','{"text":""}','{"text":"クリックで選択","clickEvent":{"action":"run_command","value":"/effect give @s minecraft:instant_health 1 20"}}']},is_waxed:1b}] 1

